# Generated by GitHub Copilot
"""LangChain retriever wrapper for pre-inference context quality filtering."""

from __future__ import annotations

from collections import defaultdict
from typing import Any, Dict, List, Mapping, Optional, Sequence

from src.watchdog import ContextWatchdog


class LangChainWatchdogRetriever:
    """Wraps a retriever and filters its results with context-watchdog."""

    def __init__(
        self,
        retriever: Any,
        watchdog: Optional[ContextWatchdog] = None,
        thresholds: Optional[Mapping[str, float]] = None,
    ) -> None:
        """Initializes a wrapper around a base retriever instance."""
        self.retriever = retriever
        self.watchdog = watchdog or ContextWatchdog()
        self.thresholds = dict(thresholds or {})
        self.last_report: Optional[Dict[str, Any]] = None

    def get_relevant_documents(self, query: str) -> List[Any]:
        """Fetches and filters documents for a query."""
        documents = list(self._fetch_documents(query))
        chunks = self._extract_chunks(documents)
        cleaned_chunks, report = self.watchdog.filter(query, chunks, self.thresholds)
        self.last_report = report
        return self._select_documents(documents, chunks, cleaned_chunks)

    def invoke(self, query: str) -> List[Any]:
        """Provides invoke-style compatibility with retriever APIs."""
        return self.get_relevant_documents(query)

    async def aget_relevant_documents(self, query: str) -> List[Any]:
        """Asynchronously fetches and filters documents when supported."""
        documents = list(await self._fetch_documents_async(query))
        chunks = self._extract_chunks(documents)
        cleaned_chunks, report = self.watchdog.filter(query, chunks, self.thresholds)
        self.last_report = report
        return self._select_documents(documents, chunks, cleaned_chunks)

    async def ainvoke(self, query: str) -> List[Any]:
        """Provides async invoke-style compatibility with retriever APIs."""
        return await self.aget_relevant_documents(query)

    def _fetch_documents(self, query: str) -> Sequence[Any]:
        """Calls the most appropriate synchronous retriever method."""
        if hasattr(self.retriever, "get_relevant_documents"):
            return self.retriever.get_relevant_documents(query)
        if hasattr(self.retriever, "invoke"):
            return self.retriever.invoke(query)
        raise AttributeError(
            "Base retriever must define get_relevant_documents(query) or invoke(query)."
        )

    async def _fetch_documents_async(self, query: str) -> Sequence[Any]:
        """Calls the most appropriate asynchronous retriever method."""
        if hasattr(self.retriever, "aget_relevant_documents"):
            return await self.retriever.aget_relevant_documents(query)
        if hasattr(self.retriever, "ainvoke"):
            return await self.retriever.ainvoke(query)
        return self._fetch_documents(query)

    @staticmethod
    def _extract_chunks(documents: Sequence[Any]) -> List[str]:
        """Converts retriever documents into plain text chunks."""
        chunks: List[str] = []
        for document in documents:
            if hasattr(document, "page_content"):
                chunks.append(str(document.page_content))
            elif isinstance(document, Mapping) and "page_content" in document:
                chunks.append(str(document["page_content"]))
            else:
                chunks.append(str(document))
        return chunks

    @staticmethod
    def _select_documents(
        documents: Sequence[Any],
        chunks: Sequence[str],
        cleaned_chunks: Sequence[str],
    ) -> List[Any]:
        """Maps filtered chunks back to the original document objects."""
        index_by_chunk: Dict[str, List[int]] = defaultdict(list)
        for index, chunk in enumerate(chunks):
            index_by_chunk[chunk].append(index)

        selected_documents: List[Any] = []
        used_indices = set()

        for chunk in cleaned_chunks:
            positions = index_by_chunk.get(chunk)
            if not positions:
                continue

            index = positions.pop(0)
            if index in used_indices:
                continue

            used_indices.add(index)
            selected_documents.append(documents[index])

        return selected_documents
