# Generated by GitHub Copilot
"""Unit tests for policy recipe helpers."""

from __future__ import annotations

import pytest

from src.policies import create_policy_watchdog, get_policy_recipe, list_policy_recipes


def test_list_policy_recipes_contains_expected_contexts() -> None:
    """Ensures Week 6 policy recipes are discoverable for adopters."""

    assert list_policy_recipes() == (
        "offline-batch",
        "realtime-support",
        "regulated-evidence",
    )


def test_get_policy_recipe_is_case_and_whitespace_tolerant() -> None:
    """Ensures policy lookup can be called with user input normalization."""

    recipe = get_policy_recipe("  Regulated-Evidence ")
    assert recipe.name == "regulated-evidence"
    assert recipe.thresholds.relevance_min == pytest.approx(0.58)


def test_get_policy_recipe_raises_for_unknown_context() -> None:
    """Ensures unknown policy names fail with actionable guidance."""

    with pytest.raises(ValueError, match="Available recipes"):
        get_policy_recipe("unknown-context")


def test_create_policy_watchdog_applies_recipe_limits_and_thresholds() -> None:
    """Ensures helper returns configured watchdog bounds and thresholds."""

    watchdog, thresholds = create_policy_watchdog("realtime-support")

    assert watchdog.max_chunks == 120
    assert watchdog.max_query_chars == 1200
    assert watchdog.max_chunk_chars == 2500
    assert thresholds == {
        "relevance_min": pytest.approx(0.32),
        "redundancy_max": pytest.approx(0.90),
        "conflict_min": pytest.approx(0.82),
    }


def test_create_policy_watchdog_applies_threshold_overrides() -> None:
    """Ensures callers can override recipe defaults safely."""

    _, thresholds = create_policy_watchdog(
        "offline-batch",
        threshold_overrides={"relevance_min": 0.51, "conflict_min": 0.61},
    )

    assert thresholds["relevance_min"] == pytest.approx(0.51)
    assert thresholds["redundancy_max"] == pytest.approx(0.86)
    assert thresholds["conflict_min"] == pytest.approx(0.61)
