# Generated by GitHub Copilot
"""Unit tests for the context-watchdog scoring and filtering flow."""

from __future__ import annotations

from dataclasses import dataclass
from io import StringIO
from typing import Any, List

from rich.console import Console

from integrations.langchain_wrapper import LangChainWatchdogRetriever
from src.report import render_report
from src.watchdog import ContextWatchdog


class FakeEmbeddingModel:
    """Provides deterministic vectors for fast tests without model downloads."""

    def encode(self, texts: List[str], **_: Any) -> List[List[float]]:
        """Encodes text into a small handcrafted feature space."""
        vectors: List[List[float]] = []
        for text in texts:
            text_lower = text.lower()
            vectors.append(
                [
                    1.0 if "database" in text_lower else 0.0,
                    1.0 if "timeout" in text_lower else 0.0,
                    1.0 if "enabled" in text_lower else 0.0,
                    1.0 if "disabled" in text_lower else 0.0,
                    1.0 if "weather" in text_lower else 0.0,
                    float(len(text_lower.split())) / 20.0,
                ]
            )
        return vectors


class FakeContradictionClassifier:
    """Returns a predictable contradiction score for selected phrase pairs."""

    def __call__(self, sequence: str, **_: Any) -> dict[str, Any]:
        """Classifies a statement pair into contradiction-related labels."""
        text = sequence.lower()
        if "enabled" in text and "disabled" in text:
            return {
                "labels": ["contradicts", "entails", "unrelated"],
                "scores": [0.92, 0.06, 0.02],
            }
        return {
            "labels": ["unrelated", "entails", "contradicts"],
            "scores": [0.80, 0.15, 0.05],
        }


@dataclass
class DummyDocument:
    """Simple document shape compatible with page_content-based retrievers."""

    page_content: str


class DummyRetriever:
    """Simple retriever mock that always returns the same documents."""

    def __init__(self, documents: List[DummyDocument]) -> None:
        """Stores a static set of documents for test retrieval."""
        self._documents = documents

    def get_relevant_documents(self, query: str) -> List[DummyDocument]:
        """Returns all stored documents while ignoring the query."""
        _ = query
        return self._documents


def _build_watchdog() -> ContextWatchdog:
    """Creates a watchdog with deterministic fake models for tests."""
    return ContextWatchdog(
        embedding_model=FakeEmbeddingModel(),
        contradiction_classifier=FakeContradictionClassifier(),
    )


def test_score_relevance_ranks_domain_chunks_higher() -> None:
    """Ensures query-matching chunks receive stronger relevance scores."""
    watchdog = _build_watchdog()
    query = "How do we fix database timeout errors?"
    chunks = [
        "Database timeout can be reduced with indexing.",
        "The weather is sunny in Madrid.",
    ]

    scores = watchdog.score_relevance(query, chunks)

    assert len(scores) == 2
    assert scores[0] > scores[1]


def test_score_redundancy_flags_high_similarity_pairs() -> None:
    """Ensures duplicate chunks are marked as redundant."""
    watchdog = _build_watchdog()
    chunks = [
        "Database timeout can be reduced with indexing.",
        "Database timeout can be reduced with indexing.",
        "Feature flag is enabled for writes.",
    ]

    report = watchdog.score_redundancy(chunks, similarity_threshold=0.85)

    assert report["redundant_pairs"]
    assert report["redundant_pairs"][0]["left"] == 0
    assert report["redundant_pairs"][0]["right"] == 1


def test_score_conflict_detects_contradictory_pairs() -> None:
    """Ensures contradictory statements are surfaced by conflict scoring."""
    watchdog = _build_watchdog()
    chunks = [
        "Feature flag is enabled for writes.",
        "Feature flag is disabled for writes.",
        "Database timeout can be reduced with indexing.",
    ]

    report = watchdog.score_conflict(chunks, conflict_threshold=0.70)

    assert report["conflict_pairs"]
    assert report["conflict_pairs"][0]["left"] == 0
    assert report["conflict_pairs"][0]["right"] == 1


def test_filter_removes_irrelevant_and_redundant_chunks() -> None:
    """Ensures filter keeps only high-value non-duplicate context chunks."""
    watchdog = _build_watchdog()
    query = "How can I fix a database timeout?"
    chunks = [
        "Database timeout can be reduced with indexing.",
        "Database timeout can be reduced with indexing.",
        "The weather is sunny in Madrid.",
    ]

    filtered, report = watchdog.filter(
        query,
        chunks,
        thresholds={"relevance_min": 0.45, "redundancy_max": 0.85, "conflict_min": 0.70},
    )

    assert len(filtered) == 1
    assert "Database timeout" in filtered[0]
    assert report["summary"]["dropped_chunks"] == 2


def test_langchain_wrapper_filters_documents() -> None:
    """Ensures wrapper returns only documents retained by watchdog filtering."""
    watchdog = _build_watchdog()
    retriever = DummyRetriever(
        documents=[
            DummyDocument("Database timeout can be reduced with indexing."),
            DummyDocument("Database timeout can be reduced with indexing."),
            DummyDocument("The weather is sunny in Madrid."),
        ]
    )

    wrapped = LangChainWatchdogRetriever(
        retriever,
        watchdog=watchdog,
        thresholds={"relevance_min": 0.45, "redundancy_max": 0.85, "conflict_min": 0.70},
    )

    filtered_docs = wrapped.get_relevant_documents("database timeout guidance")

    assert len(filtered_docs) == 1
    assert wrapped.last_report is not None
    assert "Database timeout" in filtered_docs[0].page_content


def test_render_report_produces_table_output() -> None:
    """Ensures report renderer emits expected summary fields."""
    report = {
        "summary": {"input_chunks": 3, "kept_chunks": 1, "dropped_chunks": 2},
        "chunks": [
            {
                "index": 0,
                "relevance": 0.91,
                "max_redundancy": 1.0,
                "max_conflict": 0.02,
                "kept": True,
                "drop_reasons": [],
            }
        ],
    }

    buffer = StringIO()
    console = Console(file=buffer, force_terminal=False, color_system=None)

    render_report(report, console=console)

    output = buffer.getvalue()
    assert "Input chunks" in output
    assert "Per-Chunk Quality" in output
