# Generated by GitHub Copilot
"""Top-level package for context-watchdog."""

from .policies import (
	PolicyRecipe,
	create_policy_watchdog,
	get_policy_recipe,
	list_policy_recipes,
)
from .watchdog import ContextWatchdog

__all__ = [
	"ContextWatchdog",
	"PolicyRecipe",
	"list_policy_recipes",
	"get_policy_recipe",
	"create_policy_watchdog",
]
__version__ = "0.2.0"
