# Generated by GitHub Copilot
"""Policy recipes for common context-watchdog adoption scenarios."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple

from .watchdog import ContextWatchdog, Thresholds


@dataclass(frozen=True)
class PolicyRecipe:
    """Defines thresholds and input limits for a workload context."""

    name: str
    description: str
    thresholds: Thresholds
    max_chunks: int
    max_query_chars: int
    max_chunk_chars: int

    def as_threshold_mapping(self) -> Dict[str, float]:
        """Returns thresholds in the mapping shape accepted by filter()."""

        return {
            "relevance_min": self.thresholds.relevance_min,
            "redundancy_max": self.thresholds.redundancy_max,
            "conflict_min": self.thresholds.conflict_min,
        }


_POLICY_RECIPES: Dict[str, PolicyRecipe] = {
    "realtime-support": PolicyRecipe(
        name="realtime-support",
        description="Low-latency support assistant with broad context recall and strong dedupe.",
        thresholds=Thresholds(relevance_min=0.32, redundancy_max=0.90, conflict_min=0.82),
        max_chunks=120,
        max_query_chars=1200,
        max_chunk_chars=2500,
    ),
    "regulated-evidence": PolicyRecipe(
        name="regulated-evidence",
        description="Compliance and audit workflows that prioritize precision and contradiction control.",
        thresholds=Thresholds(relevance_min=0.58, redundancy_max=0.78, conflict_min=0.55),
        max_chunks=80,
        max_query_chars=2400,
        max_chunk_chars=5000,
    ),
    "offline-batch": PolicyRecipe(
        name="offline-batch",
        description="Batch enrichment workloads in restricted environments with larger chunk windows.",
        thresholds=Thresholds(relevance_min=0.40, redundancy_max=0.86, conflict_min=0.72),
        max_chunks=350,
        max_query_chars=3000,
        max_chunk_chars=6000,
    ),
}


def list_policy_recipes() -> Sequence[str]:
    """Lists supported policy recipe names in stable order."""

    return tuple(sorted(_POLICY_RECIPES.keys()))


def get_policy_recipe(name: str) -> PolicyRecipe:
    """Returns a policy recipe by name or raises ValueError for unknown names."""

    key = str(name).strip().lower()
    recipe = _POLICY_RECIPES.get(key)
    if recipe is None:
        available = ", ".join(list_policy_recipes())
        raise ValueError(f"Unknown policy recipe '{name}'. Available recipes: {available}")
    return recipe


def create_policy_watchdog(
    name: str,
    *,
    embedding_model_name: str = "all-MiniLM-L6-v2",
    contradiction_model_name: str = "facebook/bart-large-mnli",
    embedding_model: Optional[Any] = None,
    contradiction_classifier: Optional[Any] = None,
    threshold_overrides: Optional[Mapping[str, float]] = None,
) -> Tuple[ContextWatchdog, Dict[str, float]]:
    """Builds a ContextWatchdog and threshold mapping for a named policy recipe."""

    recipe = get_policy_recipe(name)
    watchdog = ContextWatchdog(
        embedding_model_name=embedding_model_name,
        contradiction_model_name=contradiction_model_name,
        embedding_model=embedding_model,
        contradiction_classifier=contradiction_classifier,
        max_chunks=recipe.max_chunks,
        max_query_chars=recipe.max_query_chars,
        max_chunk_chars=recipe.max_chunk_chars,
    )

    resolved = Thresholds.from_mapping(
        {
            **recipe.as_threshold_mapping(),
            **(threshold_overrides or {}),
        }
    )
    return watchdog, {
        "relevance_min": resolved.relevance_min,
        "redundancy_max": resolved.redundancy_max,
        "conflict_min": resolved.conflict_min,
    }
