# Generated by GitHub Copilot
"""Rendering helpers for context-watchdog reports."""

from __future__ import annotations

from typing import Any, Mapping, Optional

from rich.console import Console
from rich.table import Table


def render_report(report: Mapping[str, Any], console: Optional[Console] = None) -> None:
    """Renders a compact quality report with summary and per-chunk diagnostics."""
    console = console or Console()

    summary = report.get("summary", {})
    summary_table = Table(title="Context Watchdog Summary")
    summary_table.add_column("Metric", style="cyan")
    summary_table.add_column("Value", justify="right", style="magenta")
    summary_table.add_row("Input chunks", str(summary.get("input_chunks", 0)))
    summary_table.add_row("Kept chunks", str(summary.get("kept_chunks", 0)))
    summary_table.add_row("Dropped chunks", str(summary.get("dropped_chunks", 0)))

    chunk_table = Table(title="Per-Chunk Quality")
    chunk_table.add_column("Index", justify="right")
    chunk_table.add_column("Relevance", justify="right")
    chunk_table.add_column("Max redundancy", justify="right")
    chunk_table.add_column("Max conflict", justify="right")
    chunk_table.add_column("Kept", justify="center")
    chunk_table.add_column("Drop reasons")

    for chunk in report.get("chunks", []):
        chunk_table.add_row(
            str(chunk.get("index", "-")),
            f"{float(chunk.get('relevance', 0.0)):.3f}",
            f"{float(chunk.get('max_redundancy', 0.0)):.3f}",
            f"{float(chunk.get('max_conflict', 0.0)):.3f}",
            "yes" if chunk.get("kept", False) else "no",
            ", ".join(chunk.get("drop_reasons", [])) or "-",
        )

    console.print(summary_table)
    console.print(chunk_table)
