# Generated by GitHub Copilot
"""Core scoring and filtering utilities for RAG context windows."""

from __future__ import annotations

import hashlib
import math
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

try:
    from sentence_transformers import SentenceTransformer
except Exception:  # pragma: no cover - optional dependency at runtime
    SentenceTransformer = None

try:
    from transformers import pipeline
except Exception:  # pragma: no cover - optional dependency at runtime
    pipeline = None


@dataclass(frozen=True)
class Thresholds:
    """Represents threshold controls used by the context filter."""

    relevance_min: float = 0.35
    redundancy_max: float = 0.85
    conflict_min: float = 0.70

    @classmethod
    def from_mapping(cls, values: Optional[Mapping[str, float]]) -> "Thresholds":
        """Creates a threshold object from an optional mapping input."""
        values = values or {}
        return cls(
            relevance_min=float(values.get("relevance_min", cls.relevance_min)),
            redundancy_max=float(values.get("redundancy_max", cls.redundancy_max)),
            conflict_min=float(values.get("conflict_min", cls.conflict_min)),
        )


class ContextWatchdog:
    """Scores and filters context chunks before they are sent to an LLM."""

    def __init__(
        self,
        embedding_model_name: str = "all-MiniLM-L6-v2",
        contradiction_model_name: str = "facebook/bart-large-mnli",
        embedding_model: Optional[Any] = None,
        contradiction_classifier: Optional[Any] = None,
    ) -> None:
        """Initializes the watchdog with optional model overrides for testability."""
        self.embedding_model_name = embedding_model_name
        self.contradiction_model_name = contradiction_model_name
        self._embedding_model = embedding_model
        self._contradiction_classifier = contradiction_classifier

    def score_relevance(self, query: str, chunks: Sequence[str]) -> List[float]:
        """Returns a 0-1 relevance score per chunk based on cosine similarity."""
        if not chunks:
            return []
        if not query.strip():
            return [0.0 for _ in chunks]

        vectors = self._encode_texts([query, *chunks])
        query_vector = vectors[0]
        chunk_vectors = vectors[1:]
        return [self._to_unit_interval(self._cosine_similarity(query_vector, vector)) for vector in chunk_vectors]

    def score_redundancy(
        self,
        chunks: Sequence[str],
        similarity_threshold: float = 0.85,
    ) -> Dict[str, Any]:
        """Calculates a pairwise similarity matrix and flags redundant chunk pairs."""
        size = len(chunks)
        if size == 0:
            return {
                "matrix": [],
                "redundant_pairs": [],
                "redundant_indices": [],
                "threshold": similarity_threshold,
            }

        vectors = self._encode_texts(chunks)
        matrix = [[1.0 if i == j else 0.0 for j in range(size)] for i in range(size)]
        redundant_pairs: List[Dict[str, Any]] = []

        for left in range(size):
            for right in range(left + 1, size):
                similarity = self._to_unit_interval(
                    self._cosine_similarity(vectors[left], vectors[right])
                )
                matrix[left][right] = similarity
                matrix[right][left] = similarity
                if similarity >= similarity_threshold:
                    redundant_pairs.append(
                        {"left": left, "right": right, "similarity": round(similarity, 4)}
                    )

        redundant_indices = sorted(
            {pair["left"] for pair in redundant_pairs}
            | {pair["right"] for pair in redundant_pairs}
        )

        return {
            "matrix": matrix,
            "redundant_pairs": redundant_pairs,
            "redundant_indices": redundant_indices,
            "threshold": similarity_threshold,
        }

    def score_conflict(
        self,
        chunks: Sequence[str],
        conflict_threshold: float = 0.70,
    ) -> Dict[str, Any]:
        """Detects conflicting chunk pairs using zero-shot NLI with heuristic fallback."""
        size = len(chunks)
        if size == 0:
            return {
                "matrix": [],
                "conflict_pairs": [],
                "conflict_indices": [],
                "threshold": conflict_threshold,
            }

        classifier = self._get_contradiction_classifier()
        matrix = [[0.0 for _ in range(size)] for _ in range(size)]
        conflict_pairs: List[Dict[str, Any]] = []

        for left in range(size):
            for right in range(left + 1, size):
                if classifier is not None:
                    score = self._classifier_contradiction_score(
                        classifier,
                        chunks[left],
                        chunks[right],
                    )
                else:
                    score = self._heuristic_conflict_score(chunks[left], chunks[right])

                matrix[left][right] = score
                matrix[right][left] = score

                if score >= conflict_threshold:
                    conflict_pairs.append(
                        {"left": left, "right": right, "conflict_score": round(score, 4)}
                    )

        conflict_indices = sorted(
            {pair["left"] for pair in conflict_pairs}
            | {pair["right"] for pair in conflict_pairs}
        )

        return {
            "matrix": matrix,
            "conflict_pairs": conflict_pairs,
            "conflict_indices": conflict_indices,
            "threshold": conflict_threshold,
        }

    def filter(
        self,
        query: str,
        chunks: Sequence[str],
        thresholds: Optional[Mapping[str, float]] = None,
    ) -> Tuple[List[str], Dict[str, Any]]:
        """Filters chunks using relevance, redundancy, and conflict constraints."""
        resolved = Thresholds.from_mapping(thresholds)

        relevance_scores = self.score_relevance(query, chunks)
        redundancy_report = self.score_redundancy(chunks, resolved.redundancy_max)
        conflict_report = self.score_conflict(chunks, resolved.conflict_min)

        redundancy_matrix = redundancy_report["matrix"]
        conflict_matrix = conflict_report["matrix"]

        ranked_indices = sorted(
            range(len(chunks)),
            key=lambda idx: relevance_scores[idx],
            reverse=True,
        )

        selected: List[int] = []
        reasons_by_chunk: Dict[int, List[str]] = {idx: [] for idx in range(len(chunks))}

        for idx in ranked_indices:
            if relevance_scores[idx] < resolved.relevance_min:
                reasons_by_chunk[idx].append("low_relevance")
                continue

            redundant_with = self._first_matrix_match(
                idx,
                selected,
                redundancy_matrix,
                resolved.redundancy_max,
            )
            if redundant_with is not None:
                reasons_by_chunk[idx].append(f"redundant_with_{redundant_with}")
                continue

            conflict_with = self._first_matrix_match(
                idx,
                selected,
                conflict_matrix,
                resolved.conflict_min,
            )
            if conflict_with is not None:
                reasons_by_chunk[idx].append(f"conflict_with_{conflict_with}")
                continue

            selected.append(idx)

        selected_set = set(selected)
        selected_sorted = sorted(selected)
        cleaned_chunks = [chunks[idx] for idx in selected_sorted]

        chunk_breakdown = []
        for idx, chunk in enumerate(chunks):
            chunk_breakdown.append(
                {
                    "index": idx,
                    "text": chunk,
                    "relevance": round(relevance_scores[idx], 4),
                    "max_redundancy": round(self._max_off_diagonal(redundancy_matrix, idx), 4),
                    "max_conflict": round(self._max_off_diagonal(conflict_matrix, idx), 4),
                    "kept": idx in selected_set,
                    "drop_reasons": reasons_by_chunk[idx],
                }
            )

        report: Dict[str, Any] = {
            "query": query,
            "thresholds": {
                "relevance_min": resolved.relevance_min,
                "redundancy_max": resolved.redundancy_max,
                "conflict_min": resolved.conflict_min,
            },
            "summary": {
                "input_chunks": len(chunks),
                "kept_chunks": len(cleaned_chunks),
                "dropped_chunks": len(chunks) - len(cleaned_chunks),
            },
            "scores": {
                "relevance": [round(score, 4) for score in relevance_scores],
                "redundancy_matrix": redundancy_matrix,
                "conflict_matrix": conflict_matrix,
            },
            "redundant_pairs": redundancy_report["redundant_pairs"],
            "conflict_pairs": conflict_report["conflict_pairs"],
            "selected_indices": selected_sorted,
            "chunks": chunk_breakdown,
        }

        return cleaned_chunks, report

    def _get_embedding_model(self) -> Optional[Any]:
        """Lazily loads the sentence-transformers model when available."""
        if self._embedding_model is not None:
            return self._embedding_model
        if SentenceTransformer is None:
            return None

        try:
            self._embedding_model = SentenceTransformer(self.embedding_model_name)
        except Exception:
            self._embedding_model = None
        return self._embedding_model

    def _get_contradiction_classifier(self) -> Optional[Any]:
        """Lazily loads a zero-shot contradiction classifier when available."""
        if self._contradiction_classifier is not None:
            return self._contradiction_classifier
        if pipeline is None:
            return None

        try:
            self._contradiction_classifier = pipeline(
                "zero-shot-classification",
                model=self.contradiction_model_name,
            )
        except Exception:
            self._contradiction_classifier = None
        return self._contradiction_classifier

    def _encode_texts(self, texts: Sequence[str]) -> List[List[float]]:
        """Encodes texts using sentence-transformers with a deterministic fallback."""
        model = self._get_embedding_model()
        if model is None:
            return [self._fallback_embedding(text) for text in texts]

        try:
            vectors = model.encode(
                list(texts),
                convert_to_numpy=False,
                normalize_embeddings=False,
            )
            return [self._to_float_vector(vector) for vector in vectors]
        except Exception:
            return [self._fallback_embedding(text) for text in texts]

    @staticmethod
    def _to_float_vector(vector: Any) -> List[float]:
        """Converts an arbitrary model vector into a plain float list."""
        return [float(value) for value in vector]

    @staticmethod
    def _cosine_similarity(left: Sequence[float], right: Sequence[float]) -> float:
        """Computes cosine similarity between two vectors."""
        dot_product = sum(a * b for a, b in zip(left, right))
        left_norm = math.sqrt(sum(a * a for a in left))
        right_norm = math.sqrt(sum(b * b for b in right))
        if left_norm == 0.0 or right_norm == 0.0:
            return 0.0
        return dot_product / (left_norm * right_norm)

    @staticmethod
    def _to_unit_interval(value: float) -> float:
        """Clamps cosine similarity into a practical 0-1 scoring range."""
        return max(0.0, min(1.0, value))

    @staticmethod
    def _max_off_diagonal(matrix: Sequence[Sequence[float]], row_index: int) -> float:
        """Returns the largest non-diagonal value for a matrix row."""
        if not matrix:
            return 0.0
        row = matrix[row_index]
        values = [value for idx, value in enumerate(row) if idx != row_index]
        return max(values, default=0.0)

    @staticmethod
    def _first_matrix_match(
        index: int,
        selected: Sequence[int],
        matrix: Sequence[Sequence[float]],
        threshold: float,
    ) -> Optional[int]:
        """Finds the first selected index whose matrix score crosses a threshold."""
        for existing in selected:
            if matrix[index][existing] >= threshold:
                return existing
        return None

    @staticmethod
    def _fallback_embedding(text: str, dimensions: int = 64) -> List[float]:
        """Creates a deterministic hashed bag-of-words embedding as a local fallback."""
        vector = [0.0] * dimensions
        for token in ContextWatchdog._tokenize(text):
            digest = hashlib.sha256(token.encode("utf-8")).hexdigest()
            index = int(digest, 16) % dimensions
            vector[index] += 1.0
        return vector

    @staticmethod
    def _tokenize(text: str) -> List[str]:
        """Tokenizes text into lowercase alphanumeric tokens."""
        return re.findall(r"[a-zA-Z0-9_]+", text.lower())

    @staticmethod
    def _classifier_contradiction_score(classifier: Any, left: str, right: str) -> float:
        """Computes contradiction probability from a zero-shot classifier response."""
        try:
            result = classifier(
                f"Statement A: {left}\nStatement B: {right}",
                candidate_labels=["contradicts", "entails", "unrelated"],
                hypothesis_template="The relationship between the statements is {}.",
            )
        except Exception:
            return ContextWatchdog._heuristic_conflict_score(left, right)

        labels = [str(label).lower() for label in result.get("labels", [])]
        scores = [float(score) for score in result.get("scores", [])]
        for label, score in zip(labels, scores):
            if "contradict" in label:
                return max(0.0, min(1.0, score))
        return 0.0

    @staticmethod
    def _heuristic_conflict_score(left: str, right: str) -> float:
        """Approximates contradiction using lexical overlap and polarity mismatch."""
        left_tokens = set(ContextWatchdog._tokenize(left))
        right_tokens = set(ContextWatchdog._tokenize(right))

        if not left_tokens or not right_tokens:
            return 0.0

        overlap = len(left_tokens & right_tokens) / max(1, min(len(left_tokens), len(right_tokens)))

        negations = {"not", "never", "no", "none", "cannot", "cant", "disabled", "false", "off"}
        positives = {"enabled", "true", "on", "allow", "allowed"}

        left_has_negation = bool(left_tokens & negations)
        right_has_negation = bool(right_tokens & negations)
        polarity_flip = left_has_negation ^ right_has_negation

        explicit_toggle = bool((left_tokens & positives) and (right_tokens & negations)) or bool(
            (right_tokens & positives) and (left_tokens & negations)
        )

        if explicit_toggle and overlap >= 0.2:
            return 0.9
        if polarity_flip and overlap >= 0.5:
            return 0.75
        if overlap >= 0.9:
            return 0.1
        return 0.05
